### ISSUE TITLE
Fails to runYarn start

### ISSUE THREAD

**Issue by jovyinny** [Neurotech-HQ/sarufi-docs#13]
This is the output i get on the terminal
![Screenshot from 2022-10-19 21-01-21](https://user-images.githubusercontent.com/71590163/196769540-44d9ed6d-f0a5-448c-a7d4-b399265afb19.png)

Any help on this?

**Comment by bkmgit** [comment]
It works for me.  Have you made any changes to the site? What commit are you building from?

**Comment by bkmgit** [comment]
Typical output once started:
```
yarn run v1.22.17
$ docusaurus start
[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at http://localhost:3000/.

✔ Client
  Compiled successfully in 2.08m


● Client █████████████████████████ done (99%) plugins 
 webpack-dev-middleware

client (webpack 5.74.0) compiled successfully
```

**Comment by jovyinny** [comment]
> It works for me. Have you made any changes to the site? What commit are you building from?

I haven't made any changes but would like to make changes but the command
```code
yarn start
```
doesn't go through

Am building from the this commit 850b17e86a2317cc4f50749162968d5826ea581a

**Comment by bkmgit** [comment]
Can you try `yarn build` on a fresh clone of the repository?

**Comment by jovyinny** [comment]
i have got the [same error as before](https://github.com/Neurotech-HQ/sarufi-docs/issues/13#issue-1415387514) after running 
```code
yarn build
```
on fresh cloned repo

**Comment by bkmgit** [comment]
Am not able to reproduce this on Fedora linux using node v16.14.0 and yarn 1.22.17.  What environment are you using?  The relevant error raising code seems to be https://github.com/facebook/docusaurus/blob/main/packages/docusaurus/bin/docusaurus.mjs#L27 Doing  a search for "SyntaxError unexpected reserved word await javascript" does show that this is a common problem though.

Checking the Docusaurus documentation https://docusaurus.io/docs/installation do you get the same problem if you try
```
yarn create docusaurus
cd my-website
yarn run start
```

**Comment by jovyinny** [comment]
Am using ubuntu 22.04 LTS
the command
```code
yarn create docusaurus
```
does not go through, this is the output i get
![Screenshot from 2022-10-22 19-06-21](https://user-images.githubusercontent.com/71590163/197349491-4f23fcb4-5c78-4bb9-b8b7-37cbdcbf85b6.png)

I tried using one of the suggestion from [codegrepper](https://www.codegrepper.com/code-examples/javascript/The+engine+%22node%22+is+incompatible+with+this+module.+Expected+version+%22%3E%3D14.17%22.+Got+%2214.16.1%22), the packages got installed but on running yarn commands the same error is displayed

**Comment by bkmgit** [comment]
Try getting Node 16, the current LTS. See https://github.com/nodesource/distributions#debinstall You will need to remove Node 12.22.9 first.

**Comment by jovyinny** [comment]
Thanks @bkmgit  Node 16 works
